namespace BuildBook.Application.BuildRecords;

public sealed record BuildRecordDetailModel(
    int Id,
    string ProductCode,
    string ProductName,
    string? ProductClassification,
    string SerialNumber,
    string? InternalStatus,
    string? CustomerName,
    string? MachineName,
    string? RadSightVersion,
    string? WindowsVersion,
    DateOnly? DateShipped,
    string? AssembledIn,
    string? AssembledBy,
    DateOnly? DateAssembled,
    string? HardwareManufacturer,
    string? ManufacturerPartNumber,
    string? ManufacturerRevision,
    string? ManufacturerSerialNumber,
    string? PackingList,
    string? CheckedBy,
    DateTimeOffset LastUpdatedAt,
    string LastUpdatedBy);
