using BuildBook.Domain.BuildRecords;

namespace BuildBook.Application.BuildRecords;

public sealed record BuildRecordDetailModel(
    int Id,
    string ProductCode,
    string ProductName,
    string? ProductClassification,
    string SerialNumber,
    string? InternalStatus,
    int? CustomerId,
    string? CustomerName,
    string? CustomerOrder,
    string? OANumber,
    string? InvoiceNumber,
    string? MachineName,
    string? PanelDeviceModel,
    string? PanelDeviceSerial,
    string? PanelFirmwareVersion,
    string? RadioSerialNumber,
    string? RouterUsed,
    string? HardwareNotes,
    string? WifiSsid,
    string? Note,
    string? DiskImageVersion,
    string? RadSightVersion,
    string? WindowsVersion,
    string? WindowsLatestPatch,
    string? BleuvioFirmwareVersion,
    string? CharthouseIrdaFirmwareVersion,
    string? RadioFirmware,
    string? RadSightUserLogin,
    string? KioskUser,
    string? WindowsAdminUser,
    DateOnly? DateShipped,
    string? AssembledIn,
    string? AssembledBy,
    DateOnly? DateAssembled,
    string? HardwareManufacturer,
    string? ManufacturerPartNumber,
    string? ManufacturerRevision,
    string? ManufacturerSerialNumber,
    string? PackingList,
    string? CheckedBy,
    IReadOnlyList<LinkedBuildRecordOrderSummary> LinkedOrders,
    IReadOnlyCollection<SecretType> SecretTypesSet,
    DateTimeOffset LastUpdatedAt,
    string LastUpdatedBy);

public sealed record LinkedBuildRecordOrderSummary(
    int OrderId,
    string OrderNumber,
    string OrderTitle,
    string Status,
    string? CustomerName,
    string? LinkType,
    DateTimeOffset LinkedAt);
