// <auto-generated />
using System;
using BuildBook.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildBook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BuildBookDbContext))]
    [Migration("20260625122323_AddBuildRecordSecretTypeUniqueIndex")]
    partial class AddBuildRecordSecretTypeUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssembledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssembledIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BleuvioFirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharthouseIrdaFirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerOrder")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("DateAssembled")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateShipped")
                        .HasColumnType("date");

                    b.Property<string>("DiskImageVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InternalStatus")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KioskUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OANumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OriginalSpreadsheetRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("PackingList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelDeviceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelDeviceSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelFirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RadSightUserLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadSightVersion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RadioFirmware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouterUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShippingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WifiSsid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindowsAdminUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindowsLatestPatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindowsVersion")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerOrder");

                    b.HasIndex("DateShipped");

                    b.HasIndex("InvoiceNumber");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("MachineName");

                    b.HasIndex("OANumber");

                    b.HasIndex("ProductCode");

                    b.HasIndex("ProductName");

                    b.HasIndex("RadSightVersion");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("WindowsVersion");

                    b.ToTable("BuildRecords");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int?>("BuildRecordId")
                        .HasColumnType("int");

                    b.Property<string>("FieldChanged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildRecordId");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("BuildRecordAudit");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildRecordId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecretType")
                        .HasColumnType("int");

                    b.Property<byte[]>("SecretValueEncrypted")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildRecordId", "SecretType")
                        .IsUnique();

                    b.ToTable("BuildRecordSecrets");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordsCreated")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("RowsRead")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("BuildBook.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecord", b =>
                {
                    b.HasOne("BuildBook.Domain.Customers.Customer", "Customer")
                        .WithMany("BuildRecords")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordAudit", b =>
                {
                    b.HasOne("BuildBook.Domain.BuildRecords.BuildRecord", "BuildRecord")
                        .WithMany("AuditEntries")
                        .HasForeignKey("BuildRecordId");

                    b.HasOne("BuildBook.Domain.BuildRecords.ImportBatch", "ImportBatch")
                        .WithMany("AuditEntries")
                        .HasForeignKey("ImportBatchId");

                    b.Navigation("BuildRecord");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordSecret", b =>
                {
                    b.HasOne("BuildBook.Domain.BuildRecords.BuildRecord", "BuildRecord")
                        .WithMany("Secrets")
                        .HasForeignKey("BuildRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecord", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.ImportBatch", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("BuildBook.Domain.Customers.Customer", b =>
                {
                    b.Navigation("BuildRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
