// <auto-generated />
using System;
using BuildBook.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildBook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BuildBookDbContext))]
    partial class BuildBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssembledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssembledIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BleuvioFirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharthouseIrdaFirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerOrder")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("DateAssembled")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateShipped")
                        .HasColumnType("date");

                    b.Property<string>("DiskImageVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InternalStatus")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KioskUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OANumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("OriginalSpreadsheetRowNumber")
                        .HasColumnType("int");

                    b.Property<string>("PackingList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelDeviceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelDeviceSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelFirmwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RadSightUserLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadSightVersion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RadioFirmware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouterUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShippingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WifiSsid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindowsAdminUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindowsLatestPatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindowsVersion")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerOrder");

                    b.HasIndex("DateShipped");

                    b.HasIndex("InvoiceNumber");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("MachineName");

                    b.HasIndex("OANumber");

                    b.HasIndex("ProductCode");

                    b.HasIndex("ProductName");

                    b.HasIndex("RadSightVersion");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("WindowsVersion");

                    b.ToTable("BuildRecords");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int?>("BuildRecordId")
                        .HasColumnType("int");

                    b.Property<string>("FieldChanged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildRecordId");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("BuildRecordAudit");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildRecordId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecretType")
                        .HasColumnType("int");

                    b.Property<byte[]>("SecretValueEncrypted")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildRecordId", "SecretType")
                        .IsUnique();

                    b.ToTable("BuildRecordSecrets");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordsCreated")
                        .HasColumnType("int");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("int");

                    b.Property<int>("RowsRead")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("BuildBook.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RmaRecordId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("RmaRecordId");

                    b.HasIndex("UploadedAt");

                    b.ToTable("RmaAttachments", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FieldChanged")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RmaRecordId")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RmaRecordId");

                    b.ToTable("RmaAudit", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("RmaRecordId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowInBoardView")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("RmaRecordId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("RmaChecklistItems", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaCommunication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CommunicationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ContactMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("date");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("bit");

                    b.Property<int>("RmaRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationDate");

                    b.HasIndex("RmaRecordId");

                    b.ToTable("RmaCommunications", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("NoteType")
                        .HasColumnType("int");

                    b.Property<int>("RmaRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoteType");

                    b.HasIndex("RmaRecordId");

                    b.ToTable("RmaNotes", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RmaRecordId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Supplier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RmaRecordId");

                    b.ToTable("RmaParts", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualRepairCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("BuildRecordId")
                        .HasColumnType("int");

                    b.Property<bool?>("ChargeableRepair")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClosureNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CollectionArranged")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("CollectionDate")
                        .HasColumnType("date");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Courier")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CustomerApprovalDate")
                        .HasColumnType("date");

                    b.Property<bool?>("CustomerApprovalReceived")
                        .HasColumnType("bit");

                    b.Property<bool?>("CustomerApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerFacingSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerImpact")
                        .HasColumnType("int");

                    b.Property<string>("CustomerReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("DataLossConcern")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("DateItemReceived")
                        .HasColumnType("date");

                    b.Property<string>("DiagnosisNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("EscalatedTo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EscalationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EscalationRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EstimatedRepairCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FaultCategory")
                        .HasColumnType("int");

                    b.Property<string>("FaultDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaultSubcategory")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FaultSummary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InitialDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitialFaultDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IntermittentFault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OnHoldReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OriginalInvoiceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OriginalPlannerNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OriginalPlannerTaskTitle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("OriginalOrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalOrderNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MigrationSource")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("Outcome")
                        .HasColumnType("int");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ProofOfDeliveryDate")
                        .HasColumnType("date");

                    b.Property<bool?>("ProofOfDeliveryReceived")
                        .HasColumnType("bit");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("QaCheckedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("QaDate")
                        .HasColumnType("date");

                    b.Property<bool?>("QaRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("QaResult")
                        .HasColumnType("int");

                    b.Property<string>("QuoteNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("ReleaseApproved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ReleaseApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReleaseApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RepairActionTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepairCompletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("RepairCompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("RepairInvoiceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReportedSymptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reproducible")
                        .HasColumnType("int");

                    b.Property<string>("ReturnAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnMethod")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RmaNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RootCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RootCauseCategory")
                        .HasColumnType("int");

                    b.Property<bool?>("SafetyConcern")
                        .HasColumnType("bit");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ShippedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ShippedDate")
                        .HasColumnType("date");

                    b.Property<string>("ShippingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupportTicketNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SupportTicketUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateOnly?>("TargetCompletionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TestDate")
                        .HasColumnType("date");

                    b.Property<string>("TestNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TestPlanUsed")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("TestRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("TestResult")
                        .HasColumnType("int");

                    b.Property<string>("TestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("WarrantyExpiryDate")
                        .HasColumnType("date");

                    b.Property<int?>("WarrantyStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("BuildRecordId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DueDate");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("Priority");

                    b.HasIndex("ProductCode");

                    b.HasIndex("ProductName");

                    b.HasIndex("RmaNumber")
                        .IsUnique();

                    b.HasIndex("SerialNumber");

                    b.HasIndex("Status");

                    b.ToTable("RmaRecords", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("RmaRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("RmaRecordId");

                    b.ToTable("RmaStatusHistory", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Security.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApplicationRoles", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Security.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WindowsUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("WindowsUserName")
                        .IsUnique();

                    b.ToTable("ApplicationUsers", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.Security.ApplicationUserRole", b =>
                {
                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId", "ApplicationRoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.ToTable("ApplicationUserRoles", (string)null);
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecord", b =>
                {
                    b.HasOne("BuildBook.Domain.Customers.Customer", "Customer")
                        .WithMany("BuildRecords")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordAudit", b =>
                {
                    b.HasOne("BuildBook.Domain.BuildRecords.BuildRecord", "BuildRecord")
                        .WithMany("AuditEntries")
                        .HasForeignKey("BuildRecordId");

                    b.HasOne("BuildBook.Domain.BuildRecords.ImportBatch", "ImportBatch")
                        .WithMany("AuditEntries")
                        .HasForeignKey("ImportBatchId");

                    b.Navigation("BuildRecord");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecordSecret", b =>
                {
                    b.HasOne("BuildBook.Domain.BuildRecords.BuildRecord", "BuildRecord")
                        .WithMany("Secrets")
                        .HasForeignKey("BuildRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaAttachment", b =>
                {
                    b.HasOne("BuildBook.Domain.Rmas.RmaRecord", "RmaRecord")
                        .WithMany("Attachments")
                        .HasForeignKey("RmaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RmaRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaAudit", b =>
                {
                    b.HasOne("BuildBook.Domain.Rmas.RmaRecord", "RmaRecord")
                        .WithMany("AuditEntries")
                        .HasForeignKey("RmaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RmaRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaChecklistItem", b =>
                {
                    b.HasOne("BuildBook.Domain.Rmas.RmaRecord", "RmaRecord")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("RmaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RmaRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaCommunication", b =>
                {
                    b.HasOne("BuildBook.Domain.Rmas.RmaRecord", "RmaRecord")
                        .WithMany("Communications")
                        .HasForeignKey("RmaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RmaRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaNote", b =>
                {
                    b.HasOne("BuildBook.Domain.Rmas.RmaRecord", "RmaRecord")
                        .WithMany("Notes")
                        .HasForeignKey("RmaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RmaRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaPart", b =>
                {
                    b.HasOne("BuildBook.Domain.Rmas.RmaRecord", "RmaRecord")
                        .WithMany("Parts")
                        .HasForeignKey("RmaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RmaRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaRecord", b =>
                {
                    b.HasOne("BuildBook.Domain.BuildRecords.BuildRecord", "BuildRecord")
                        .WithMany()
                        .HasForeignKey("BuildRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BuildBook.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BuildRecord");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaStatusHistory", b =>
                {
                    b.HasOne("BuildBook.Domain.Rmas.RmaRecord", "RmaRecord")
                        .WithMany("StatusHistoryEntries")
                        .HasForeignKey("RmaRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RmaRecord");
                });

            modelBuilder.Entity("BuildBook.Domain.Security.ApplicationUserRole", b =>
                {
                    b.HasOne("BuildBook.Domain.Security.ApplicationRole", "ApplicationRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildBook.Domain.Security.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.BuildRecord", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("BuildBook.Domain.BuildRecords.ImportBatch", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("BuildBook.Domain.Customers.Customer", b =>
                {
                    b.Navigation("BuildRecords");
                });

            modelBuilder.Entity("BuildBook.Domain.Rmas.RmaRecord", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditEntries");

                    b.Navigation("ChecklistItems");

                    b.Navigation("Communications");

                    b.Navigation("Notes");

                    b.Navigation("Parts");

                    b.Navigation("StatusHistoryEntries");
                });

            modelBuilder.Entity("BuildBook.Domain.Security.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BuildBook.Domain.Security.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
